Repository chen-tf/price-tracker-bot, pull requests merged in 2022-12, with the labels that each got.

#15 [Dev] add pull request template
  .github/pull_request_template.md
Labels: documentation

#19 [Dev] add docker compose file and postgresql inside
  docker-compose.yml
  sqls/create_tables.sql
Labels: enhancement

#20 [Dev] apply dependabot
  .github/dependabot.yml
Labels: enhancement

#29 :bug: Update beta_cd.yml
  .github/workflows/beta_cd.yml
Labels: bug
